version: "3.7"

services:
  app:
    image: docker.io/bitnami/laravel:8.5.24
    ports:
      - "8000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE=${DB_DATABASE}
    volumes:
      - ".:/app"

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    working_dir: /var/lib/mysql
    volumes:
      - ./.docker/mysql:/var/lib/mysql

  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080
